from app.schemas.company import (
    CompanyBase,
    CompanyCreate,
    CompanyUpdate,
    CompanyRead,
)

from app.schemas.site import (
    SiteBase,
    SiteCreate,
    SiteUpdate,
    SiteRead,
)

from app.schemas.equipment import (
    EquipmentBase,
    EquipmentCreate,
    EquipmentUpdate,
    EquipmentRead,
)

from app.schemas.sensor import (
    SensorBase,
    SensorCreate,
    SensorUpdate,
    SensorRead,
)

from app.schemas.measurement import (
    MeasurementBase,
    MeasurementCreate,
    MeasurementUpdate,
    MeasurementRead,
)

from app.schemas.maintenance import (
    MaintenanceBase,
    MaintenanceCreate,
    MaintenanceUpdate,
    MaintenanceRead,
)

from app.schemas.dashboard import (
    AssetOverview,
    CategoryCount,
    CompletedMaintenanceSummary,
    CorrectiveMaintenanceSummary,
    CountKPI,
    CoverageSummary,
    DailyMeasurementCount,
    DashboardPeriod,
    DashboardRead,
    DashboardScope,
    DowntimeSummary,
    EquipmentCriticalitySummary,
    EquipmentStatusSummary,
    LastMeasurement,
    MaintenanceCostSummary,
    MaintenancePrioritySummary,
    MaintenanceSummary,
    MaintenanceTypeSummary,
    MeasurementActivitySummary,
    MeasurementQualitySummary,
    MeasurementSummary,
    OpenMaintenanceSummary,
    OverdueMaintenanceSummary,
    RatioKPI,
    SensorCoverageSummary,
    SensorStatusSummary,
)

__all__ = [
    "CompanyBase",
    "CompanyCreate",
    "CompanyUpdate",
    "CompanyRead",
    "SiteBase",
    "SiteCreate",
    "SiteUpdate",
    "SiteRead",
    "EquipmentBase",
    "EquipmentCreate",
    "EquipmentUpdate",
    "EquipmentRead",
    "SensorBase",
    "SensorCreate",
    "SensorUpdate",
    "SensorRead",
    "MeasurementBase",
    "MeasurementCreate",
    "MeasurementUpdate",
    "MeasurementRead",
    "MaintenanceBase",
    "MaintenanceCreate",
    "MaintenanceUpdate",
    "MaintenanceRead",
    "AssetOverview",
    "CategoryCount",
    "CompletedMaintenanceSummary",
    "CorrectiveMaintenanceSummary",
    "CountKPI",
    "CoverageSummary",
    "DailyMeasurementCount",
    "DashboardPeriod",
    "DashboardRead",
    "DashboardScope",
    "DowntimeSummary",
    "EquipmentCriticalitySummary",
    "EquipmentStatusSummary",
    "LastMeasurement",
    "MaintenanceCostSummary",
    "MaintenancePrioritySummary",
    "MaintenanceSummary",
    "MaintenanceTypeSummary",
    "MeasurementActivitySummary",
    "MeasurementQualitySummary",
    "MeasurementSummary",
    "OpenMaintenanceSummary",
    "OverdueMaintenanceSummary",
    "RatioKPI",
    "SensorCoverageSummary",
    "SensorStatusSummary",
]
