"""create sensors table

Revision ID: 572080d9e581
Revises: 656260b06cdf
Create Date: 2026-09-01 16:54:04.136224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '572080d9e581'
down_revision: Union[str, Sequence[str], None] = '656260b06cdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('sensor_type', sa.String(length=100), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensors_code'), 'sensors', ['code'], unique=True)
    op.create_index(op.f('ix_sensors_equipment_id'), 'sensors', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_sensors_id'), 'sensors', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sensors_id'), table_name='sensors')
    op.drop_index(op.f('ix_sensors_equipment_id'), table_name='sensors')
    op.drop_index(op.f('ix_sensors_code'), table_name='sensors')
    op.drop_table('sensors')
    # ### end Alembic commands ###
