"""add equipment criticality

Revision ID: 675ebfea0bb5
Revises: 783e16aa6ce3
Create Date: 2026-09-02 15:40:32.163169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '675ebfea0bb5'
down_revision: Union[str, Sequence[str], None] = '783e16aa6ce3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipments', sa.Column('criticality', sa.String(length=20), nullable=False, server_default='medium'))
    op.create_index(op.f('ix_equipments_criticality'), 'equipments', ['criticality'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_equipments_criticality'), table_name='equipments')
    op.drop_column('equipments', 'criticality')
    # ### end Alembic commands ###
