"""create maintenance records table

Revision ID: 783e16aa6ce3
Revises: 570ce155aaf8
Create Date: 2026-09-02 15:10:31.868915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '783e16aa6ce3'
down_revision: Union[str, Sequence[str], None] = '570ce155aaf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenance_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('maintenance_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('failure_code', sa.String(length=50), nullable=True),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('action_taken', sa.Text(), nullable=True),
    sa.Column('technician', sa.String(length=150), nullable=True),
    sa.Column('planned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('downtime_minutes', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_records_equipment_id'), 'maintenance_records', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_maintenance_records_failure_code'), 'maintenance_records', ['failure_code'], unique=False)
    op.create_index(op.f('ix_maintenance_records_id'), 'maintenance_records', ['id'], unique=False)
    op.create_index(op.f('ix_maintenance_records_maintenance_type'), 'maintenance_records', ['maintenance_type'], unique=False)
    op.create_index(op.f('ix_maintenance_records_planned_at'), 'maintenance_records', ['planned_at'], unique=False)
    op.create_index(op.f('ix_maintenance_records_status'), 'maintenance_records', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_maintenance_records_status'), table_name='maintenance_records')
    op.drop_index(op.f('ix_maintenance_records_planned_at'), table_name='maintenance_records')
    op.drop_index(op.f('ix_maintenance_records_maintenance_type'), table_name='maintenance_records')
    op.drop_index(op.f('ix_maintenance_records_id'), table_name='maintenance_records')
    op.drop_index(op.f('ix_maintenance_records_failure_code'), table_name='maintenance_records')
    op.drop_index(op.f('ix_maintenance_records_equipment_id'), table_name='maintenance_records')
    op.drop_table('maintenance_records')
    # ### end Alembic commands ###
